// front/src/components/core/link-text/link-text.tsx
import {component$, Slot} from "@builder.io/qwik";
import {Link as QwikLink} from "@builder.io/qwik-city";
import {LinkTextPropsType, linkTextStyles} from "~/components/core/link-text/link-text-variant";
import {cn} from "~/utils/classe-name/cn";

export const LinkText = component$<LinkTextPropsType>(({
    variant = 'blue',
    size = 'base',
    href,
    external = false,
    class: className,
    ...props
}) => {
    const linkClasses = cn(
        linkTextStyles.base,
        linkTextStyles.variants[variant],
        linkTextStyles.sizes[size],
        className
    );

    // Si c'est un lien externe ou commence par http/https, utiliser un <a> normal
    if (external || href.startsWith('http://') || href.startsWith('https://') || href.startsWith('mailto:') || href.startsWith('tel:')) {
        return (
            <a 
                {...props} 
                href={href} 
                class={linkClasses}
                target={external ? '_blank' : undefined}
                rel={external ? 'noopener noreferrer' : undefined}
            >
                <Slot/>
            </a>
        );
    }

    // Sinon, utiliser le Link de Qwik pour la navigation interne
    return (
        <QwikLink 
            {...props} 
            href={href} 
            class={linkClasses}
        >
            <Slot/>
        </QwikLink>
    );
});

// app/src/components/core/link-text/link-text.component.ts
import {Component, computed, input} from '@angular/core';
import {RouterLink} from '@angular/router';
import {cn} from '../../../utils/class-name/cn';
import {LinkTextVariantProps, linkTextVariants} from './link-text.variant';
import {NgTemplateOutlet} from '@angular/common';

type VV<K extends keyof LinkTextVariantProps> = NonNullable<LinkTextVariantProps[K]>;

@Component({
  selector: 'c-link-text',
  imports: [
    RouterLink,
    NgTemplateOutlet
  ],
  template: `
    <ng-template #content>
      <ng-content/>
    </ng-template>

    @if (isExternal()) {
      <a [href]="url()" rel="noopener noreferrer" target="_blank" (click)="handleClick($event)" [class]="classes()">
        <ng-container [ngTemplateOutlet]="content"/>
      </a>
    } @else {
      <a [routerLink]="url()" (click)="handleClick($event)" [class]="classes()">
        <ng-container [ngTemplateOutlet]="content"/>
      </a>
    }
  `,

})
export class LinkTextComponent {
  // variants
  readonly color = input<VV<'color'>>('blue');
  readonly size = input<VV<'size'>>('base');
  readonly underline = input<VV<'underline'>>('hover');

  // props
  readonly url = input.required<string>();
  readonly className = input<string>('', { alias: 'class' });
  readonly external = input<boolean>(false);

  readonly classes = computed(() =>
    cn(
      linkTextVariants({
        color: this.color(),
        size: this.size(),
        underline: this.underline()
      }),
      this.className()
    )
  );

  readonly isExternal = computed(() =>{
    return this.external() || this.isExternalUrl();
  })

  // au changement d'url, on vérifie si c'est une url externe
  private readonly isExternalUrl = computed(() => {
    const url = this.url();
    return url?.startsWith('http://') ||
      url?.startsWith('https://') ||
      url?.startsWith('mailto:') ||
      url?.startsWith('tel:');
  });

  handleClick(event: Event) {
    if (!this.url()) {
      event.preventDefault();
      return;
    }
  }
}
