// app/src/components/core/text/text.component.ts
import {BlockquoteVariantProps, blockquoteVariants, MessageVariantProps, messageVariants, TextVariantProps, textVariants} from './text.variant';
import {Component, computed, input} from '@angular/core';
import {cn} from '../../../utils/class-name/cn';

type VVT<K extends keyof TextVariantProps> = NonNullable<TextVariantProps[K]>;
type VVTM<K extends keyof MessageVariantProps> = NonNullable<MessageVariantProps[K]>;
type VVTBQ<K extends keyof BlockquoteVariantProps> = NonNullable<BlockquoteVariantProps[K]>;

@Component({
  selector: 'c-text',
  template: `
    <p [class]="classes()"><ng-content></ng-content></p>
  `,
})
export class TextComponent {
  readonly variant = input<VVT<'variant'>>('paragraph');
  readonly size    = input<VVT<'size'>>('base');
  readonly weight  = input<VVT<'weight'>>('normal');
  readonly align   = input<VVT<'align'>>('left');
  readonly color   = input<VVT<'color'>>('default');
  readonly className = input<string>('', { alias: 'class' });

  readonly classes = computed(() =>
    cn(textVariants({
      variant: this.variant(),
      size: this.size(),
      weight: this.weight(),
      align: this.align(),
      color: this.color(),
    }), this.className())
  );
}

@Component({
  selector: 'c-text-message',
  template: `
    <p [class]="classes()"><ng-content></ng-content></p>
  `,
})
export class TextMessageComponent {
  readonly variant = input<VVTM<'variant'>>('info');
  readonly size    = input<VVTM<'size'>>('base');
  readonly className = input<string>('', { alias: 'class' });

  readonly classes = computed(() =>
    cn(messageVariants({
      variant: this.variant(),
      size: this.size(),
    }), this.className())
  );
}

@Component({
  selector: 'c-text-blockquote',
  template: `
    <blockquote [class]="classes()"><ng-content/></blockquote>
  `,
})
export class TextBlockquoteComponent {
  readonly variant = input<VVTBQ<'variant'>>('default');
  readonly className = input<string>('', { alias: 'class' });

  readonly classes = computed(() =>
    cn(blockquoteVariants({ variant: this.variant() }), this.className())
  );
}

// front/src/components/core/text/text.tsx
import {component$, Slot} from "@builder.io/qwik";
import {TextProps, MessageProps, BlockquoteProps, textVariants, messageVariants, blockquoteVariants} from "~/components/core/text/text-variant";
import {cn} from "~/utils/classe-name/cn";


export const Text = component$<TextProps>(({
    variant = 'paragraph',
    size = 'base',
    weight = 'normal',
    align = 'left',
    color = 'default',
    class: className,
    ...props
}) => {
    return (
        <p {...props} class={cn(textVariants({variant, size, weight, align, color}), className)}>
            <Slot/>
        </p>
    )
});

export const Message = component$<MessageProps>(({
    variant = 'info',
    size = 'base',
    class: className,
    ...props
}) => {
    return (
        <div {...props} class={cn(messageVariants({variant, size}), className)}>
            <Slot/>
        </div>
    )
});

export const Blockquote = component$<BlockquoteProps>(({
    variant = 'default',
    class: className,
    ...props
}) => {
    return (
        <blockquote {...props} class={cn(blockquoteVariants({variant}), className)}>
            <Slot/>
        </blockquote>
    )
});

// ----------------------------- Composants pré-configurés pour des cas d'usage spécifiques ----------------------------- //

// Composants de texte
export const Paragraph = component$<Omit<TextProps, 'variant'>>((props) => (
    <Text variant="paragraph" {...props}>
        <Slot/>
    </Text>
));

export const SmallText = component$<Omit<TextProps, 'variant' | 'size'>>((props) => (
    <Text variant="small" size="sm" {...props}>
        <Slot/>
    </Text>
));

export const Caption = component$<Omit<TextProps, 'variant' | 'size'>>((props) => (
    <Text variant="caption" size="xs" {...props}>
        <Slot/>
    </Text>
));

export const Lead = component$<Omit<TextProps, 'variant' | 'size'>>((props) => (
    <Text variant="lead" size="lg" {...props}>
        <Slot/>
    </Text>
));

export const MutedText = component$<Omit<TextProps, 'variant'>>((props) => (
    <Text variant="muted" {...props}>
        <Slot/>
    </Text>
));

export const CodeText = component$<Omit<TextProps, 'variant'>>((props) => (
    <Text variant="code" {...props}>
        <Slot/>
    </Text>
));

// Composants de message
export const SuccessMessage = component$<Omit<MessageProps, 'variant'>>((props) => (
    <Message variant="success" {...props}>
        <Slot/>
    </Message>
));

export const ErrorMessage = component$<Omit<MessageProps, 'variant'>>((props) => (
    <Message variant="error" {...props}>
        <Slot/>
    </Message>
));

export const WarningMessage = component$<Omit<MessageProps, 'variant'>>((props) => (
    <Message variant="warning" {...props}>
        <Slot/>
    </Message>
));

export const InfoMessage = component$<Omit<MessageProps, 'variant'>>((props) => (
    <Message variant="info" {...props}>
        <Slot/>
    </Message>
));

// Composants de citation
export const DefaultQuote = component$<Omit<BlockquoteProps, 'variant'>>((props) => (
    <Blockquote variant="default" {...props}>
        <Slot/>
    </Blockquote>
));

export const PrimaryQuote = component$<Omit<BlockquoteProps, 'variant'>>((props) => (
    <Blockquote variant="primary" {...props}>
        <Slot/>
    </Blockquote>
));

export const SuccessQuote = component$<Omit<BlockquoteProps, 'variant'>>((props) => (
    <Blockquote variant="success" {...props}>
        <Slot/>
    </Blockquote>
));

export const WarningQuote = component$<Omit<BlockquoteProps, 'variant'>>((props) => (
    <Blockquote variant="warning" {...props}>
        <Slot/>
    </Blockquote>
));

export const ErrorQuote = component$<Omit<BlockquoteProps, 'variant'>>((props) => (
    <Blockquote variant="error" {...props}>
        <Slot/>
    </Blockquote>
));
